version: "3.8"

x-shared:
  zammad-service: &zammad-service
    image: ghcr.io/zammad/zammad:6.5.2-46
    restart: always
    environment:
      MEMCACHE_SERVERS: zammad-memcached:11211
      POSTGRESQL_DB: zammad_production
      POSTGRESQL_HOST: zammad-postgresql
      POSTGRESQL_USER: zammad
      POSTGRESQL_PASS: zammad
      POSTGRESQL_PORT: 5432
      POSTGRESQL_OPTIONS: "?pool=50"
      REDIS_URL: redis://zammad-redis:6379

      # Zammad DI-BELAKANG HTTPS PROXY
      ZAMMAD_HTTP_TYPE: http
      ZAMMAD_FQDN: 172.20.240.69
      RAILS_TRUSTED_PROXIES: 172.20.240.0/24

      TZ: Asia/Jakarta

    volumes:
      - zammad-storage:/opt/zammad/storage
    networks:
      - zammad-net

services:
  zammad-init:
    <<: *zammad-service
    command: ["zammad-init"]
    restart: on-failure
    user: 0:0

  zammad-postgresql:
    image: postgres:17.7-alpine
    restart: always
    environment:
      POSTGRES_DB: zammad_production
      POSTGRES_USER: zammad
      POSTGRES_PASSWORD: zammad
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - zammad-net

  zammad-memcached:
    image: memcached:1.6-alpine
    command: memcached -m 256M
    restart: always
    networks:
      - zammad-net

  zammad-redis:
    image: redis:7.4-alpine
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - zammad-net

  zammad-railsserver:
    <<: *zammad-service
    command: ["zammad-railsserver"]

  zammad-scheduler:
    <<: *zammad-service
    command: ["zammad-scheduler"]

  zammad-websocket:
    <<: *zammad-service
    command: ["zammad-websocket"]

  zammad-nginx:
    <<: *zammad-service
    command: ["zammad-nginx"]
    ports:
      - "8080:8080"
    depends_on:
      - zammad-railsserver

volumes:
  postgresql-data:
  redis-data:
  zammad-storage:

networks:
  zammad-net:
    driver: bridge
