version: "3.8"

services:
  nginx-https-proxy:
    image: nginx:alpine
    container_name: zammad-https-proxy
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl:ro
    networks:
      - zammad-net

networks:
  zammad-net:
    external: true
    name: zammad_zammad-net
